two changes: 1.tiny clean of mysocketio 2.add device id 0x31 0x33 0x34 0x35

diff --git a/scripts/ble-backend-nan b/scripts/ble-backend-nan
--- a/scripts/ble-backend-nan
+++ b/scripts/ble-backend-nan
@@ -24,10 +24,13 @@ while [ $# -gt 0 ]; do
       ;;
     -command=starttest)
       echo "**$1 $2 $3 $4 $5**"
-      # for i in {1..30}; do echo "hello, $i"; sleep 1; done
-      sleep 3
-      # act as failure
-      # exit 1
+      # 1. act as output
+      for i in {1..10}; do echo "hello, $i"; sleep 1; done;
+      # 2. no database insert
+      # exit 0
+      sleep 1
+      # 3. act as failure
+      # exit 10
       for i in {1..50}; do
       mysql -p123456 -e "INSERT ge.testdatas(devicecode, factorycode, fw_version, rssi_ble1, rssi_ble2, rssi_wifi1, rssi_wifi2, mac_ble, mac_wifi, status_cmd_check1, status_cmd_check2, bool_qualified_signal, bool_qualified_check, bool_qualified_scan, bool_qualified_deviceid, datetime, reserve_str_1, reserve_bool_1) VALUES(13, 1, '3.1', -65, -65, -33, -33, 'f4:bc:da:70:4c:20', '010203040506', 11111, 11111, true, true, true, true, now(), '222', true)"
       if [ $i -eq 5 ]; then
